### ISSUE TITLE
Action fails with `act` error

### ISSUE THREAD

**Issue by acatxnamedvirtue** [qoomon/actions--parallel-steps#5]
Hi,

Running a step with this action fails with this error:
```
Error: unknown command "act" for "gh" - 
```

I did come up with a workaround, right before this, I have a separate step that installs the extension:

```
- name: Install Act
   run: gh extension install nektos/gh-act
   env:
      GH_TOKEN: ${{ github.token }}
```
